on:
  release:
    types: [created]

name: Upload release assets
jobs:
  build:
    name: build binaries
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: build
      run: |
        export GO111MODULE=on
        make build
        for f in bin/*; do tar cvzf $f.tar.gz $f; rm $f; done
        cp README.md bin/
    - name: upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: bin/

  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build artefacts
        uses: actions/download-artifact@v1
        with:
          name: binaries
          path: bin/
      - name: Upload release assets
        uses: skx/github-action-publish-binaries@9f2ea568baec5017a7d608f03ef143a57745cc5c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './bin/*'
